const MODULES = [
  ['Company','business','Company Setup','modules/company-setup.html'],['Company','business','Branch','modules/branch.html'],
  ['Bank','account_balance','Bank Setup','modules/bank-setup.html'],['Bank','account_balance','Cheque Book','modules/cheque-book.html'],
  ['CRM','groups','Client Details','modules/client-details.html'],['CRM','groups','Contacts','modules/contacts.html'],
  ['Accounts','account_balance_wallet','Ledgers','modules/ledgers.html'],['Accounts','account_balance_wallet','Vouchers','modules/vouchers.html'],['Accounts','account_balance_wallet','Transactions','modules/transactions.html'],['Accounts','account_balance_wallet','Cash Book','modules/cash-book.html'],['Accounts','account_balance_wallet','Bank Book','modules/bank-book.html'],
  ['Compliance','task_alt','Task','modules/task.html'],['Compliance','key','Credentials','modules/credentials.html'],
  ['Projects','folder','Projects Details','modules/projects-details.html'],
  ['Employee','badge','Employee Details','modules/employee-details.html'],['Employee','badge','Attendance','modules/attendance.html'],['Employee','badge','Pay Slip','modules/pay-slip.html'],
  ['Appointment','event','Appointment Data','modules/appointment-data.html'],
  ['Data','import_export','Import','modules/import.html'],['Data','import_export','Export','modules/export.html'],['Data','import_export','Backup','modules/backup.html'],['Data','import_export','Restore','modules/restore.html'],
  ['Templates','description','Invoice','modules/invoice-template.html'],['Templates','description','Estimate','modules/estimate-template.html'],['Templates','description','Receipt Voucher','modules/receipt-voucher-template.html'],['Templates','description','Payment Voucher','modules/payment-voucher-template.html'],['Templates','description','Pay Slip','modules/payslip-template.html'],['Templates','description','Letter Head','modules/letter-head-template.html'],['Templates','description','Experience Certificate','modules/experience-certificate-template.html'],['Templates','description','Office Seal','modules/office-seal-template.html'],['Templates','description','Accounts Statements','modules/accounts-statements-template.html'],
  ['Reports','analytics','Reports','modules/reports.html'],
  ['BIQ Integration','hub','Setup Payment Gateway','modules/payment-gateway.html'],['BIQ Integration','hub','Setup UPI','modules/setup-upi.html'],['BIQ Integration','hub','Bank Details','modules/integration-bank-details.html'],['BIQ Integration','hub','Send Due Alert','modules/send-due-alert.html'],['BIQ Integration','hub','Send Bill/Estimate','modules/send-bill-estimate.html'],['BIQ Integration','hub','Send Vouchers','modules/send-vouchers.html'],
  ['Documents','folder_open','Documents Upload / View','modules/documents.html'],
  ['User Profile','person','User Profile','modules/user-profile.html'],
  ['More','more_horiz','App Info and Version','modules/app-info.html'],['More','more_horiz','Plan and Subscription','modules/plan-subscription.html'],['More','more_horiz','Privacy & Refund','modules/privacy-refund.html'],['More','more_horiz','Theme & Style','modules/theme-style.html']
];
function nav(){const c=document.getElementById('nav-container'); if(!c)return; let last=''; c.innerHTML=MODULES.map(([section,icon,title,path])=>{let h='';if(section!==last){last=section;h=`<div class="px-4 pb-2 pt-5 text-[11px] font-bold tracking-wider text-m3-outline uppercase">${section}</div>`}return h+`<a href="${path}" data-link class="nav-item flex items-center gap-3 px-4 py-2.5 rounded-full text-m3-onSurfaceVariant hover:bg-m3-surfaceContainerHigh transition-colors"><span class="material-symbols-outlined text-[20px]">${icon}</span><span class="label-lg font-medium">${title}</span></a>`}).join('')}
function setup(){nav(); document.body.addEventListener('click',e=>{const a=e.target.closest('[data-link]');if(a){e.preventDefault();location.href=a.getAttribute('href')}});const b=document.getElementById('mobileMenuBtn'),s=document.getElementById('sidebar'),back=document.getElementById('sidebarBackdrop');if(b)b.onclick=()=>{s.classList.add('open');back.classList.remove('hidden')};if(back)back.onclick=()=>{s.classList.remove('open');back.classList.add('hidden')};}
function validateField(el){if(!el.value)return true; if(el.dataset.regex){try{return new RegExp(el.dataset.regex).test(el.value.toUpperCase())}catch(e){return true}}return true}
function wireValidation(){document.querySelectorAll('input[data-regex]').forEach(i=>i.addEventListener('blur',()=>{if(!validateField(i))i.setCustomValidity(i.dataset.message||'Invalid format');else i.setCustomValidity('')}));document.querySelectorAll('form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();if(!f.reportValidity())return;const out=f.querySelector('.save-result');if(out)out.textContent='Specification validated locally. No data was submitted.';}));}
function boot(){setup();wireValidation();}
document.addEventListener('DOMContentLoaded',boot);
